name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"